### ISSUE TITLE
Consider removing Axios in favour of node-fetch

### ISSUE THREAD

**Issue by nickytonline** [raae/gatsby-remark-oembed#119]
`fetch` is not native in Node yet (I think they're working on it), but there is [node-fetch](https://www.npmjs.com/package/node-fetch).

It has a way smaller footprint than Axios and the extra stuff Axios provides is not required in the project from what I can tell. This change would also require pulling out the `axios-mock-adapter` package and replacing it with most likely [jest-fetch-mock](https://www.npmjs.com/package/jest-fetch-mock).

## Documents and Links

- Relates to #116
- [Axios on Bundlephobia](https://bundlephobia.com/result?p=axios@0.21.0), 13.4kB MINIFIED 4.6kB MINIFIED + GZIPPED
- [node-fetch on Bundlephobia](https://bundlephobia.com/result?p=node-fetch@2.6.1), 452B MINIFIED 289B MINIFIED + GZIPPED

**Comment by raae** [comment]
I just really like working with Axios ;D

**Comment by nickytonline** [comment]
I'll close this then @raae.
