### ISSUE TITLE
Consider adding lint-staged to be used with husky for a Git pre-commit hook

### ISSUE THREAD

**Issue by nickytonline** [raae/gatsby-remark-oembed#120]
It's great that the project is already using the husky package for Git hooks. Currently there is a Git pre-push hook. Consider a pre-commit hook using lint-staged. Having a pre-commit hook can lint (potentially fix issues), run prettier and also be able to run tests related to the files being changed.

For an example of this in the wild, see https://github.com/forem/forem/blob/master/package.json#L30-L75

## Documents and Links

- [lint-staged](https://github.com/okonet/lint-staged)
- [Stuff I always Set Up for Frontend Work](https://dev.to/nickytonline/stuff-i-always-set-up-for-frontend-work-56h2)
- https://github.com/typicode/husky/issues/677

**Comment by raae** [comment]
Yeah, that would be great!
