### ISSUE TITLE
Consider adding the Dependabot app to the project

### ISSUE THREAD

**Issue by nickytonline** [raae/gatsby-remark-oembed#121]
Consider adding the Dependabot app to the project to manage dependency updates. Dependabot can create pull requests, rebase if necessary etc and will run through CI like any PR which will lessen the burden of keeping up to date with packages used in the project.

Check out the [official Dependabot\(https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/) post about being integrated into GitHub.

**Comment by raae** [comment]
Is it not? I do have some PRs merged from them.

**Comment by nickytonline** [comment]
Ahh that's my bad. For some reason I didn't think it was on the repo. I'll close this then.
