### ISSUE TITLE
Something is up with Twitch embeds

### ISSUE THREAD

**Issue by raae** [raae/gatsby-remark-oembed#129]
They are not being embedded in the example sites, neither locally or on Netlify.

**Comment by raae** [comment]
v5 of Twitch API is deprecated and it seems v6 does not have oEmbed support.

iamcal/oembed#437

**Comment by dpi** [comment]
xpost https://discuss.dev.twitch.tv/t/oembed-deprecation/24424/3?u=dpi

**Comment by M0nica** [comment]
Should this plugin deprecate Twitch in light of this update from Twitch? It seems, from what I am reading, since their oEmbed functionality wasn’t publicly documented it was quietly deprecated on their end.

**Comment by raae** [comment]
The plugin uses the official list over on oembed.com, but it seems that Twitch should be removed from that list and then this project should remove all references to Twitch.

Just makes me so sad that oEmbed support is being dropped.

**Comment by raae** [comment]
Would you like to do it @M0nica? 

Add a PR for the removal of Twitch at https://github.com/iamcal/oembed and then add a notice in our docs.

**Comment by raae** [comment]
I created a PR over in the oEmbed repo iamcal/oembed#495.
