### ISSUE TITLE
trim option should exclude <pre>

### ISSUE THREAD

**Issue by danielimmke** [raae/gatsby-remark-oembed#146]
Using this without `trim: true` causes errors but with trim true it messes up stuff inside `<pre>` elements, which are supposed to retain their white space. I can try to put in a PR for this if you will merge it.

**Comment by danielimmke** [comment]
Whoops - wrong repository! I have too many tabs open.

**Comment by raae** [comment]
No worries, you are welcome to contribute at any time though :D
