### ISSUE TITLE
Twitter Embed - Missing blockquote.twitter-tweet

### ISSUE THREAD

**Issue by vincro** [raae/gatsby-remark-oembed#149]
per instructions at the bottom of the page:

https://developer.twitter.com/en/docs/twitter-for-websites/embedded-tweets/overview

the rendered `blockquote` does not have the `twitter-tweet` class, and so then `twttr.widgets.load()` is called as it is in the gatsby-browser.js file of the plugin, it doesn't end up being styled.

**Comment by vincro** [comment]
Discovered the HTML from the JSON response was being put through a sanitizer

**Comment by vincro** [comment]
Discovered the HTML from the JSON response was being put through a sanitizer =)

**Comment by raae** [comment]
Happy you figured it out 🎉
