### ISSUE TITLE
Ready for use?

### ISSUE THREAD

**Issue by chmac** [raae/gatsby-remark-oembed#33]
First, thanks for creating this plugin. It's a great idea to be able to throw a simple URL into a post and have it turn into a proper embed. WordPress solves this problem nicely already, and it's great to have something similar in Gatsby.

Is the plugin ready for use? I saw something in another thread about it being ready for alpha in a week or two (which was ~4 weeks ago I think). Is it ready for testing now?

I saw the issue around caching in #25. I didn't understand if that issue is a show stopper or not. Did you find a workaround? Anything I could do to help out?

**Comment by raae** [comment]
Hi, thanks for your interest. 

It is ready for testing, but I am awaiting a fix for this bug https://github.com/gatsbyjs/gatsby/issues/8788 meaning you have to use a gatsby version between 2.0.0 and 2.0.17. Not above.

To help out right now would be to test it and report back if you have any problems.

**Comment by chmac** [comment]
Aha, I feared that the Gatsby issue might be a blocker. I think I'm already running a later version. :-( I've posted a follow up on that issue to see where it's at, maybe I can help out there to get it moving.

**Comment by raae** [comment]
It should now be ready for use.
