### ISSUE TITLE
Some Twitter links don't load correctly

### ISSUE THREAD

**Issue by felipesere** [raae/gatsby-remark-oembed#34]
I use this plugin to embedd some tweets on my page.
This worked pretty neatly so far, until this morning I noticed that two had loaded the content but not the correct Twitter styling.

There was nothing unusual in the network tab and no errors in the console.

I have attached two screenshots and their respective location in the my site.
Maybe there is something you can spot? 

<img width="822" alt="screenshot 2018-12-02 at 14 28 50" src="https://user-images.githubusercontent.com/1850188/49340965-c2b75480-f63e-11e8-9da2-b8a6027d278f.png">

https://www.felipesere.com/blog/2017-01-25-fast-feedback-with-rspec-and-rerun

and the failing ones:
<img width="1193" alt="screenshot 2018-12-02 at 14 29 00" src="https://user-images.githubusercontent.com/1850188/49340973-d498f780-f63e-11e8-8108-d83dd275e023.png">
https://www.felipesere.com/advent/?day=1

**Comment by raae** [comment]
Thanks for reaching out.

When that happens the Twitter javascript has not loaded. Why I am not sure. What gatsby version are you on?

I will try to look into this on Wednesday.

**Comment by felipesere** [comment]
I am at the latest version of Gatsby that still works with oembed.
If you want to point me in any direction I can give it a whirl.

Do you load the JS via Helmet?

**Comment by raae** [comment]
I think it might have to do with using a popup. The Twitter code needs to be ran after the content is on the page.

**Comment by raae** [comment]
So either have it on the page, but hidden, so the js picks it up when page load is done. Or  manually run the code.

**Comment by felipesere** [comment]
I've had to do it via a `setTimeout(() => loadTwitter(), 100)` because I can't tell when react will have rendered my component into the DOM... 😢

**Comment by jbhannah** [comment]
I've run into a similar issue: visiting a page with an embedded tweet doesn't load the Twitter embed code on the initial page load, but subsequent navigation between pages does trigger the change.

**Comment by jbhannah** [comment]
Looking at the code, I think this may be why:

https://github.com/raae/gatsby-remark-oembed/blob/bb1df40dc139e886eeba4f04c8c0db7a468e0383/gatsby-browser.js#L23-L26

These might also have to be called [`onInitialClientRender`](https://www.gatsbyjs.org/docs/browser-apis/#onInitialClientRender). (My [homepage](https://jbhannah.net) is where I've run into this.)

**Comment by raae** [comment]
Could you test going directly to https://gatsby-remark-oembed.netlify.com/twitter/, that is a page with an embedded tweet. 

Will try to look more into this next week.
