### ISSUE TITLE
Custom styling to Codepen iframe

### ISSUE THREAD

**Issue by florinpop17** [raae/gatsby-remark-oembed#39]
Is it possible to add styles like: `width` and `height` to a Codepen Embed?

**Comment by florinpop17** [comment]
I found the class in the iframe afterall! 😅

**Comment by raae** [comment]
Great news, any and all issues makes me happy because it means my plugin is in use and that makes me happy :D

**Comment by raae** [comment]
This will actually be possible after pull request #38 is merged as long as the provider supports it. 

It seems Codepen only has support for height: https://blog.codepen.io/documentation/api/oembed/#height-adjusting-5

**Comment by florinpop17** [comment]
Well, you can set the desired width and height on the iframe in your CSS.
