### ISSUE TITLE
Disable logging

### ISSUE THREAD

**Issue by rayriffy** [raae/gatsby-remark-oembed#40]
This plugin is always flooding my console all the time. Is there any options to disable them?

![](https://storage.rayriffy.com/files/image/71Z9ipFs3wLqDZwrBD.png)

**Comment by raae** [comment]
Not yet!

Thanks for letting me know this is an issue for you :D

**Comment by rayriffy** [comment]
I reccomended to make some pattern for this plugin to avoid any scaning other URLs.
For an exmaple, https://gist.github.com/rayriffy/12651d2ba8db582846f2bf8497ffdde1

**Comment by mjm** [comment]
I'd like to be able to disable the logging as well (at least for non-error cases). Would you be open to a PR to add an option for that?

(Love the plugin btw)

**Comment by raae** [comment]
I am going to merge in @rayriffy's latest PR and then do some cleanup (also of issues).

If I do not get to refactoring logging during that work then I would love a PR. I'll let you know by Wednesday :D If not logging there will be other possible tasks.

**Comment by mjm** [comment]
Cool cool! Just let me know and I’d be happy to contribute :)

**Comment by raae** [comment]
Next release will solve this, by having a "summary" as below for everything that is not a proper error.

```
info gatsby-remark-oembed: Found 10 possible link(s)
info gatsby-remark-oembed: Successfully embedded 8 link(s)
warning gatsby-remark-oembed: 2 link(s) did not match a provider
```

**Comment by raae** [comment]
I have made it even denser it now outputs only one summary line per markdown file with oembed links.

```
info gatsby-remark-oembed: Successfull embeds: 8 | Path: /bunchofstuff/
```

Please test and report back in #55 .
