### ISSUE TITLE
Codepen request failed with status code 403

### ISSUE THREAD

**Issue by florinpop17** [raae/gatsby-remark-oembed#45]
For some reason since Codepen was attacked, the embeds aren't working anymore on my [blog](https://florin-pop/com/blog/). I get a `Request failed with status code 403` at build time.

Do you think that this is something that can be fixed in this package or maybe is caused by them?

**Comment by raae** [comment]
I am inclined to think this is because they are trying to prevent dos attacks by shutting down endpoints or something. 

Thanks for letting me know, and I will try to figure out where exactly it is failing to see if there is anything we can do.

**Comment by florinpop17** [comment]
I think you are right!
Would love to see if you can fix this! ☺️

On Medium the link embeds are working, maybe this could help? See what are they doing to go around it

**Comment by raae** [comment]
Yes, their oembed endpoint is moved behind a captcha form and also if you try to manually embed iframes it seems iframe embeds are broken. 

They might not have done this intentionally so I will let them know. Trying first with a (polite I hope) tweet.

https://twitter.com/raae/status/1115504689355923456

**Comment by raae** [comment]
This seems to have been resolved. Let me know if it still not working for you @florinpop17.

**Comment by kennethormandy** [comment]
> Yes, their oembed endpoint is moved behind a captcha form

This seems to have resurfaced for me. It seems like requesting the CodePen URL always returns a 403 and hits the Cloudflare captcha form page. I’m seeing it when I try to regenerate the test sites in this repo, and my own sites. I’ve tried it locally and via CI with GitHub Actions, so I don’t think it’s specific to me.

<img width="1066" alt="Screen Shot 2021-01-23 at 12 33 19 PM" src="https://user-images.githubusercontent.com/1581276/105613544-0833c000-5d78-11eb-9883-8d0024c4c557.png">

<img width="740" alt="Screen Shot 2021-01-23 at 12 33 43 PM" src="https://user-images.githubusercontent.com/1581276/105613546-0b2eb080-5d78-11eb-9558-8b35a628c041.png">

**Comment by raae** [comment]
Its not much the plugin can do when the oEmbed endpoints does not answer correctly. 

Hardcoding the code that it should answer with (for instance) kind of go again the whole oEmbed concept.

I am however planning a major overhaul of this plugin this spring and will look at ways to possibly solve cases like this.

**Comment by raae** [comment]
I asked again on Twitter what they are up to @kennethormandy.

https://twitter.com/raae/status/1356888855878787072
