### ISSUE TITLE
Add support for an array of prefixes

### ISSUE THREAD

**Issue by raae** [raae/gatsby-remark-oembed#47]
Lets users define their own prefixes like `video:`.

This would give users more control over their content, and also make it easier to migrate from other plugins were other prefixes have been used.

There are plugins for youtube, twitter etc. specifically. And the users of those will probably have lots of content already using a specific prefix.

In config `usePrefix: ["video:", "oembed:"]`.

**Comment by rayriffy** [comment]
Cool idea! I will try a workaround with this.
