### ISSUE TITLE
Error on links that is not oembed able

### ISSUE THREAD

**Issue by osj2507** [raae/gatsby-remark-oembed#48]
This is somewhat related to https://github.com/raae/gatsby-remark-oembed/issues/40 but also a bit different, but this issue does the same as for issue 40, my console is flooded.

I am getting a lot of "error No endpoint for ..." because I am using links to other sites that are not oembed enabled and shouldn't be, I am not using the prefix (it is easier that way) but it seems that this tries all links even though it should not IMHO.

So I would like to get an error in my console if something is wrong with a link, but not errors for links that aren't supported, but let's say I use an embed link from youtube, then it should fail if that doesn't work.

Other than that, it's a great plugin and I don't need to run multiple different ones to embed from Youtube, Twitter, and Instagram, so very happy.

**Comment by raae** [comment]
Yes, I totally agree with that and will take that into consideration when solving #40.

**Comment by raae** [comment]
Next release will solve this, but having a "summary" as below for everything that is not a proper error.

```
info gatsby-remark-oembed: Found 10 possible link(s)
info gatsby-remark-oembed: Successfully embedded 8 link(s)
warning gatsby-remark-oembed: 2 link(s) did not match a provider
```

**Comment by raae** [comment]
I have made it even denser it now outputs only one summary line per markdown file with oembed links.

```
info gatsby-remark-oembed: Successfull embeds: 8 | Path: /bunchofstuff/
```

Please test and report back in #55 .
