### ISSUE TITLE
Testing version 0.0.7

### ISSUE THREAD

**Issue by raae** [raae/gatsby-remark-oembed#55]
I would love to get some help testing 0.0.7.

It fixes the problem up cluttering up the log, but it's also a major refactor and it would be nice to get confirmation that it is still working for y'all.

cc: @osj2507, @florinpop17, @rayriffy, @amykapernick, @mjm @nickytonline 

Install the git tag by using `npm install raae/gatsby-remark-oembed#semver:0.0.7`

**Comment by nickytonline** [comment]
I'll take a peek later tonight @raae

**Comment by mjm** [comment]
I can give it a try tomorrow evening!

**Comment by nickytonline** [comment]
@raae, I installed `raae/gatsby-remark-oembed#semver:0.0.7` and all looks good. No errors in the console and things display properly.

:shipit:

**Comment by osj2507** [comment]
If I just install the updated version, my links are no longer converted, am using the non-prefix version.
If I go back, everything works great, so are there any change I need to be aware of setup wise that has changed?

I did get an error at first
Error: Cannot find module 'gatsby-source-filesystem'
Installed that and then got errors like below for all my links

```
error gatsby-remark-oembed: Error processing links
  TypeError: Cannot read property 'replace' of undefined
  - index.js:10 module.exports
    [project]/[slash]/index.js:10:13
  - create-file-path.js:39 module.exports
    [project]/[gatsby-source-filesystem]/create-file-path.js:39:61  
  - index.js:24 module.exports
    [project]/[@raae]/gatsby-remark-oembed/index.js:24:20
  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7
```

I will say I am still new to gatsby and node, so I might be doing something wrong :(

**Comment by eshlox** [comment]
It works for me, no errors. ;-)

**Comment by eshlox** [comment]
I'm not sure if it's related to version 0.0.7 but it tries to transform Markdown links which are surrounded by empty lines.

Example:

```markdown
test

[Test](https://github.com/raae/gatsby-remark-oembed)

test
```

`gatsby develop` logs:

```
info gatsby-remark-oembed: Successfull embeds: 0 | Links with no matching provider: 1 | Path: /test/
```

**Comment by nickytonline** [comment]
I didn't look for that @eshlox. I'll take a peek later tonight to see if I have this behaviour.

**Comment by raae** [comment]
If you are not using 'usePrefix: true' it will try to convert all links surrounded by empty lines @eshlox.

**Comment by raae** [comment]
Will have a look @osj2507, do you have an example markdowns file for me or a repo to look at. And did it work before with 0.0.6?

**Comment by rayriffy** [comment]
Everything looks good for me!

**Comment by nickytonline** [comment]
> I didn't look for that @eshlox. I'll take a peek later tonight to see if I have this behaviour.

All good on my end still, including links markdown links.

**Comment by mjm** [comment]
All is working well for me, and the log output is definitely easier to read and understand.

I do still kind of wish that I could silence the successful cases completely though. I have lots of small posts on my site, and many of them have embeds, so the logging is still pretty chatty.

**Comment by raae** [comment]
I hear you @mjm, will try to add an option for that.

**Comment by raae** [comment]
Nudge @osj2507, do you have any example markdown or repo I could look at to reproduce this error?

**Comment by raae** [comment]
I read your error message again @osj2507 and it might be something with the cache not cleared after installing the pluging `gatsby-source-filesystem`.

I will release this and then do a separate one for even more silent logging @mjm.
