### ISSUE TITLE
Possible DoS attack on current axios version

### ISSUE THREAD

**Issue by rayriffy** [raae/gatsby-remark-oembed#56]
More detail
https://snyk.io/vuln/SNYK-JS-AXIOS-174505

**Comment by rayriffy** [comment]
Closing this because there's look like no issue at all

**Comment by raae** [comment]
Good to hear! I have not had time to look into it.

**Comment by raae** [comment]
It has now turned up as an official security issue! I do not think its to bad for us as we do not use it in the browser and the crash would potentially just crash the build.

**Comment by raae** [comment]
This has been fixed in v0.19.0.

**Comment by raae** [comment]
Also a v0.18.1 fix https://github.com/axios/axios/releases/tag/v0.18.1

**Comment by rayriffy** [comment]
0.19.0 is now on latest stable release. I will open PR to update this thing tonight.
