### ISSUE TITLE
Keep a local copy of the provider list

### ISSUE THREAD

**Issue by raae** [raae/gatsby-remark-oembed#64]
I do not have any reports of https://oembed.com/providers.json not responding, but it could be nice to have a local copy to fall back if that happens. 

It could be cool if the file was downloaded and added to the project on every npm publish or something automatic like that to keep it as current as possible.

**Comment by raae** [comment]
This might be something for you @testower.

**Comment by testower** [comment]
Cool I'll have a look @raae

**Comment by testower** [comment]
Did you try this yet @raae ?

**Comment by raae** [comment]
Yes and merged!
