### ISSUE TITLE
Gatsby swag anyone ?

### ISSUE THREAD

**Issue by raae** [raae/gatsby-remark-oembed#69]
Hey all contributors @rayriffy, @yurm04, @muescha, @kennethormandy, @nickytonline, @testower, and @olavea.

I have gotten a gift card to the Gatsby swag shop as thanks for being a guest on the webinar yesterday. Would any of you like something?

**Comment by nickytonline** [comment]
That'd be awesome!

I already have a pair of their socks, so if anyone else doesn't have any swag yet go ahead. Otherwise, I definitely wouldn't say no to more Gatsby swag 😉

**Comment by yurm04** [comment]
Nice of you to share!!

I also have some swag from Gatsby so everyone else can have dibs.  After that, I’ve had my eye on that gatsby pin 🙃

**Comment by rayriffy** [comment]
OMG! I just hear that they also have Gatsby swag lol.

Now I added label pin and sticker pack on my wishlist. (✧ω✧)

**Comment by raae** [comment]
> OMG! I just hear that they also have Gatsby swag lol.
> 
> Now I added label pin and sticker pack on my wishlist. (✧ω✧)

Will get some for you!

**Comment by raae** [comment]
> Nice of you to share!!
> 
> I also have some swag from Gatsby so everyone else can have dibs. After that, I’ve had my eye on that gatsby pin 🙃

We can definitely hook you up with a pin!

**Comment by raae** [comment]
> That'd be awesome!
> 
> I already have a pair of their socks, so if anyone else doesn't have any swag yet go ahead. Otherwise, I definitely wouldn't say no to more Gatsby swag 😉

What type of swag, check out https://store.gatsbyjs.org/? Anything 10 and down should be ok for me to ship from Norway.

**Comment by nickytonline** [comment]
I see the black t-shirts are 10$. If that works, I'd take a large unisex one. Thanks in advance!

**Comment by raae** [comment]
Will order this weekend. It all has to be shipped to me before I can ship it to you. So this might take some time ;D

**Comment by nickytonline** [comment]
No rush and thanks for the kind gesture.

**Comment by raae** [comment]
Would you like a t-shirt as well @rayriffy?

**Comment by rayriffy** [comment]
I would like a purple MD unisex one, please.

**Comment by raae** [comment]
Has arrived in Oslo, will ask for everyone's addresses when I am home from vacay office :D

![D_M2ikxXkAA6lAV](https://user-images.githubusercontent.com/478531/61063560-6ef4c100-a400-11e9-800a-022e9246e8ae.jpg)

**Comment by raae** [comment]
It's through customs and I will be able to pick it up this week. Please send your postal address to raae@raae.codes.

**Comment by raae** [comment]
@yurm04 send me your address and you will get a pin (and a pair of socks).

**Comment by raae** [comment]
We shipped of the swag! 
The family helped out :D 

![20190822_200429](https://user-images.githubusercontent.com/478531/63567723-01958d80-c573-11e9-8f02-7997074c7986.jpg)

**Comment by nickytonline** [comment]
The t-shirt has landed @raae. Thanks so much! 🔥🙌💯

![11E50426-228A-40EF-931C-727EB3D58117](https://user-images.githubusercontent.com/833231/63974169-51e08400-ca7a-11e9-8029-6a5bb23b8941.jpeg)

**Comment by raae** [comment]
Somehow @rayriffy came back to us, will send it again!

**Comment by rayriffy** [comment]
Don't worry! I can wait (just a little more lol)

![](https://cdn.discordapp.com/attachments/577046038716874762/616876513270431764/IMG_5386.jpg)

PS. Last weekend I hosted the very first Gatsby meetup in Thailand with some help with my friends...that is also the first event that I ever host in my life :)

![](https://cdn.discordapp.com/attachments/577046038716874762/616876847124185118/IMG_5354.jpeg)
