### ISSUE TITLE
Logging only works with markdown sourced from gatsby-source-filesystem, not contentful

### ISSUE THREAD

**Issue by patroza** [raae/gatsby-remark-oembed#73]
```
    "@raae/gatsby-remark-oembed": "^0.0.7",
    "gatsby": "^2.8.3",
    "gatsby-transformer-remark": "^2.3.12",
```
*Have more installed, happy to share*

```
error gatsby-remark-oembed: Error processing links


  TypeError: Cannot read property 'replace' of undefined

  - index.js:10 module.exports
    [starter-gatsby-blog]/[gatsby-source-filesystem]/[slash]/index.js:10:13

  - create-file-path.js:39 module.exports
    [starter-gatsby-blog]/[gatsby-source-filesystem]/create-file-path.js:39:61

  - index.js:24 module.exports
    [starter-gatsby-blog]/[@raae]/gatsby-remark-oembed/index.js:24:20

  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7
```

happens with just `"@raae/gatsby-remark-oembed"` in the plugins of `"gatsby-transformer-remark"` as well as with the given samples for the configuration.

**Comment by raae** [comment]
Thank you for letting us know, do you have a public repo I could look at?

**Comment by raae** [comment]
Nudge @patroza?

**Comment by patroza** [comment]
hi @raae sorry for late reply; don't have the project public right now, but what I found so far is that it probably doesnt support the markdown content to live on contentful instead of on disk?
ie I use `"gatsby-source-contentful"` not `-filesystem`

**Comment by patroza** [comment]
So it looks like contentful based files have no `relativePath` property, while `gatsby-source-filesystem` expects it to exist.

if in `gatsby-source-filesystem` I replace the `return fileNode` statement with:
` return fileNode.internal.type !== `File` ? undefined : fileNode`

the app works, and the oembed works. it logs:
`info gatsby-remark-oembed: Successfull embeds: 1 | Path: undefined`

**Comment by raae** [comment]
Thank you for that insight.

This should be easily fixed as I was only trying to make a more informative logging experience. In this case`Path: undefinded`. So it is not crucial to make the plugin work, I'll let you know when this is fixed.

**Comment by raae** [comment]
I am now using the markdown node's id, instead of trying to get the path. 

Could you test if it works with contentful by `npm install raae/gatsby-remark-oembed#logging-bug-#73` to use the branch with the fix?

**Comment by raae** [comment]
I managed to create a contentful space to test it out and it works fine.

**Comment by patroza** [comment]
Great to hear @raae, sorry for late response, missed notification somehow
