### ISSUE TITLE
Testing version 0.1.0

### ISSUE THREAD

**Issue by raae** [raae/gatsby-remark-oembed#82]
I would love to get some help testing 0.1.0.

You can now configure an array of prefixes. So if you already use `usePrefix: true`, test with `usePrefix: ["oembed", "test"]` and change some of the prefixed links to `` `test: http.....` ``.

cc: @osj2507, @florinpop17, @rayriffy, @amykapernick, @mjm @nickytonline, @testower, @muescha, @yurm04, @victornguyen.

For the next release, I will have set up a yarn workspace with several test sites configured and there will be less need for manual testing.

Install the git tag by using `npm install raae/gatsby-remark-oembed#semver:0.1.0`

**Comment by testower** [comment]
I found an issue while testing: the prefetched list was ignored by npm pack because of .gitignore, so it needs to be unignored by .npmignore to be included in the package. Added a PR for the fix: #83, @raae

**Comment by raae** [comment]
Here is an example post!

`usePrefix: ["oembed", "video"]` should result in the video embedding twitce.
```
---
title: Vimeo Embed
date: "2018-10-03"
---

Embedded Vimeo video!

https://vimeo.com/42672205

`video: https://vimeo.com/42672205`

`oembed: https://vimeo.com/42672205`

Look at that :D
```

**Comment by testower** [comment]
Everything looks good to me @raae (except for #83) :)

**Comment by raae** [comment]
It's out as 0.1.1.

When I am done with #76 is done I will move us into proper versioning, starting at 1.0.0 👊
